#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="docs/PROJECT_STATUS.md"
NOW_UTC="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

GIT_BRANCH="$(git branch --show-current || echo unknown)"
GIT_HEAD="$(git rev-parse --short HEAD || echo unknown)"
GIT_LAST="$(git log -1 --pretty=format:'%h %s (%ad)' --date=short || echo unknown)"

SERVICE_COUNT="$(find services -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
SKILL_COUNT="$(find workspace/skills -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
DASH_API_COUNT="$(find apps/alchemical-dashboard/app/api -type f -name 'route.ts' | wc -l | tr -d ' ')"
GATEWAY_ENDPOINT_COUNT="$(grep -E "^@app\.(get|post|put|delete)\(" gateway/app.py | wc -l | tr -d ' ')"

SERVICES_LIST="$(find services -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)"
SKILLS_LIST="$(find workspace/skills -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)"

{
  echo "# Project Status Snapshot"
  echo
  echo "_Auto-generated from repository state. Do not edit manually._"
  echo
  echo "## Metadata"
  echo
  echo "- Generated: **$NOW_UTC**"
  echo "- Branch: **$GIT_BRANCH**"
  echo "- HEAD: **$GIT_HEAD**"
  echo "- Last commit: **$GIT_LAST**"
  echo
  echo "## Repository Metrics"
  echo
  echo "| Metric | Value |"
  echo "|---|---:|"
  echo "| Runtime services | $SERVICE_COUNT |"
  echo "| Skills repos | $SKILL_COUNT |"
  echo "| Dashboard API routes | $DASH_API_COUNT |"
  echo "| Gateway endpoints | $GATEWAY_ENDPOINT_COUNT |"
  echo
  echo "## Runtime Services (from /services)"
  echo
  echo '```text'
  echo "$SERVICES_LIST"
  echo '```'
  echo
  echo "## Skills (from /workspace/skills)"
  echo
  echo '```text'
  echo "$SKILLS_LIST"
  echo '```'
  echo
  echo "## Notes"
  echo
  echo '- This file is generated by: `scripts/sync-project-state.sh`'
  echo '- Trigger this manually with: `bash scripts/sync-project-state.sh`'
  echo "- Also updated automatically by CI on push and schedule."
} > "$OUT"

echo "Updated $OUT"
